### ISSUE TITLE
Two recipes files are empty: sweet-potato-casserole-iii and sugarless-fruitcake

### ISSUE THREAD

**Issue by PLNech** [dpapathanasiou/recipes#4]
Hi, thanks for the lovely repo! I noticed two files are empty:
```
Error loading sweet-potato-casserole-iii.json: Expecting value: line 1 column 1 (char 0)
Error loading sugarless-fruitcake.json: Expecting value: line 1 column 1 (char 0)
```

We might want to rerun the data loading for these two, or to delete the empty files for consistency? :)

**Comment by dpapathanasiou** [comment]
Hello @PLNech and thank you for spotting these.

The corresponding URLs are these:

- http://allrecipes.com/recipe/8026/sugarless-fruitcake/
- https://www.allrecipes.com/recipe/13496/sweet-potato-casserole-iii/

But it's been a very long time since I tried using the [recipebook](https://github.com/dpapathanasiou/recipebook/) app, and it turns out it needs some updates: https://github.com/dpapathanasiou/recipebook/issues/3

So until I can sort that out, I'm just going to remove these two files, and all the references to them.
